In [53]:
import torch

In [54]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available Using GPU")

GPU not available Using GPU


## 1) Creating a Tensor

In [55]:
a = torch.empty(2,3)

In [56]:
type(a)

torch.Tensor

In [57]:
# Using Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [58]:
# torch rand ( give random value btw 0-1)
torch.rand(2,3)

tensor([[0.1780, 0.3011, 0.1893],
        [0.9186, 0.2131, 0.3957]])

In [59]:
# manual_seed ( use same value while rand show diff value when we run again )
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [60]:
# print same value as upper
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [61]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [62]:
# arange 
print("Using arange ->",torch.arange(0,10,2))  #done slicing

#using linspace
print("\nUsing linspace ->",torch.linspace(0,10,10)) #range 0-10 evenly space 10 no

# using eye 
print("\nUsing eye -> \n",torch.eye(5)) # print identity matrix

# using full
print("\nUsing full -> \n", torch.full((3,3),5)) # matrix 3 X 3 of no 5

Using arange -> tensor([0, 2, 4, 6, 8])

Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

Using eye -> 
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

Using full -> 
 tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tesnor Shape

In [63]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)
x.shape

tensor([[1, 2, 3],
        [4, 5, 6]])


torch.Size([2, 3])

In [64]:
# make another tensor with same shape
torch.empty_like(x)

tensor([[4611686018427387904, 4595145985553858560, 4601585856296255488],
        [4597248719937601536, 4606222999341760512, 4587329636848893952]])

In [65]:
torch.zeros_like(x) # use one also

tensor([[0, 0, 0],
        [0, 0, 0]])

In [66]:
# below code give error bcz x is int while rand give float

#torch.rand_like(x)

## Tensor Data type

In [67]:
# find data type
x.dtype

torch.int64

In [68]:
# assign data type 
torch.tensor([1.0,2.0,3.0],dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [69]:
torch.tensor([1.0,2.0,3.0],dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [70]:
# Using .to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## 2) Mathmatical operation on tensor

In [71]:
# addition 
print("Addition: \n",x + 2)

# substraction 

print("Substraction : \n",x -2)

# Multiplication 

print("Multiplication : \n",x *2)

# int Division
print("Division : \n",x // 2)

# pow 

print("Power : \n",x **2)



Addition: 
 tensor([[3, 4, 5],
        [6, 7, 8]])
Substraction : 
 tensor([[-1,  0,  1],
        [ 2,  3,  4]])
Multiplication : 
 tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
Division : 
 tensor([[0, 1, 1],
        [2, 2, 3]])
Power : 
 tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [72]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

# tensor addition
print("Addition :\n",a+b) #same as sub,mul,div,mod,pow

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])
tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])
Addition :
 tensor([[0.9745, 0.8304, 0.6263],
        [1.0195, 1.1186, 1.4921]])


In [73]:
c= torch.tensor([1,-2,3,-4])

# some more operation 

# abs
print('Absolute value:\n',torch.abs(c))

# negative
print('\nNegative value:\n',torch.neg(c))

d = torch.tensor([1.9,2.3,3.7,4.4])

#Round
print('\nRound value:\n',torch.round(d))

# Ceil
print('\nCeil value:\n',torch.ceil(d)) # move to next int

# floor
print('\nFloor value:\n',torch.floor(d)) # prev int

#clamp
print('\nClamp value:\n',torch.clamp(d,min=2, max=3))  # less than 2 -> 2 , greter than 3 -> 3 ( Certain range)



Absolute value:
 tensor([1, 2, 3, 4])

Negative value:
 tensor([-1,  2, -3,  4])

Round value:
 tensor([2., 2., 4., 4.])

Ceil value:
 tensor([2., 3., 4., 5.])

Floor value:
 tensor([1., 2., 3., 4.])

Clamp value:
 tensor([2.0000, 2.3000, 3.0000, 3.0000])


## 3) Reduction operation 

In [74]:
e = torch.randint(size=(2,3), low=0,high=10,dtype=torch.float32)
print(e)

# sum ( for whole)
print("\nSum of all :\n",torch.sum(e))

# Sum along column
print("\nSum of col :\n",torch.sum(e,dim=0))

# sum of rows
print("\nSum of row :\n",torch.sum(e,dim=1))

tensor([[4., 3., 8.],
        [7., 4., 6.]])

Sum of all :
 tensor(32.)

Sum of col :
 tensor([11.,  7., 14.])

Sum of row :
 tensor([15., 17.])


In [75]:
# mean 
torch.mean(e)

tensor(5.3333)

In [76]:
# max and min ( we can to col and row wise also )
torch.max(e)
torch.min(e)

tensor(3.)

In [77]:
# Standard deviation
print("standard deviation :",torch.std(e))

# argmax  ( position of gretest no )
print("Argmax :",torch.argmax(e))  

# argmin  ( position of smallest no )
print("Argmin :",torch.argmin(e))  

standard deviation : tensor(1.9664)
Argmax : tensor(2)
Argmin : tensor(1)


## 4) Matrix Operation

In [78]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[0, 1, 9],
        [9, 8, 0]])
tensor([[7, 0],
        [0, 9],
        [5, 7]])


In [79]:
# matrix multiplication 
torch.matmul(f,g)

tensor([[45, 72],
        [63, 72]])

In [80]:
# dot product
vec1 = torch.tensor([1,2])
vec2 = torch.tensor([3,4])

torch.dot(vec1,vec2)

tensor(11)

In [81]:
# transpose
print(f)
torch.transpose(f,0,1)

tensor([[0, 1, 9],
        [9, 8, 0]])


tensor([[0, 9],
        [1, 8],
        [9, 0]])

In [82]:
# determinant 
h = torch.randint(size=(2,2),low=0, high=10, dtype=torch.float32)
print(h)
torch.det(h)

tensor([[3., 9.],
        [4., 0.]])


tensor(-36.)

## 5) Comparison operation

In [83]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[5, 7, 5],
        [9, 9, 7]])
tensor([[5, 9, 8],
        [9, 7, 9]])


In [84]:
# greter than 
print("Greater than:\n",i > j)

# leas than
print("\nLess than:\n",i < j)

# Equal to
print("\nLess than:\n",i == j)

Greater than:
 tensor([[False, False, False],
        [False,  True, False]])

Less than:
 tensor([[False,  True,  True],
        [False, False,  True]])

Less than:
 tensor([[ True, False, False],
        [ True, False, False]])


## 6) Special function

In [85]:
k = torch.randint(size=(2,3), low=0, high=10,dtype=torch.float32)
print(k)

tensor([[2., 6., 7.],
        [7., 8., 3.]])


In [86]:
# log
torch.log(k)

tensor([[0.6931, 1.7918, 1.9459],
        [1.9459, 2.0794, 1.0986]])

In [87]:
#sqrt
torch.sqrt(k)

tensor([[1.4142, 2.4495, 2.6458],
        [2.6458, 2.8284, 1.7321]])

In [88]:
#sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.9975, 0.9991],
        [0.9991, 0.9997, 0.9526]])

In [89]:
#softmax 
torch.softmax(k,dim=0)


tensor([[0.0067, 0.1192, 0.9820],
        [0.9933, 0.8808, 0.0180]])

In [90]:
# relu 
torch.relu(k)

tensor([[2., 6., 7.],
        [7., 8., 3.]])

## 7) Inplace Ooperation
use '_' to make it permanent change

In [91]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print('\n')
print(n)

tensor([[0.9053, 0.8356, 0.3039],
        [0.6726, 0.5740, 0.9233]])


tensor([[0.9178, 0.7590, 0.7775],
        [0.6179, 0.3379, 0.2170]])


In [92]:
# add m and n and store in m to save space
m.add_(n)
print(m)

tensor([[1.8231, 1.5946, 1.0814],
        [1.2905, 0.9118, 1.1403]])


## Copying a Tensor

In [93]:
a = torch.rand(2,3)
a

tensor([[0.9454, 0.7116, 0.1157],
        [0.6574, 0.3451, 0.0453]])

In [94]:
# make copy of a
b = a
b

tensor([[0.9454, 0.7116, 0.1157],
        [0.6574, 0.3451, 0.0453]])

In [95]:
# problem 
a[0][0] = 0
print(a)

# 0 index of b also change if we change a
print(b)

tensor([[0.0000, 0.7116, 0.1157],
        [0.6574, 0.3451, 0.0453]])
tensor([[0.0000, 0.7116, 0.1157],
        [0.6574, 0.3451, 0.0453]])


In [ ]:
# fix 
b = a.clone()
print(b)
print('\n')

a[0][0] = 2
print(a)

# now b not chnge on changing a
print('\n')
print(b)

tensor([[0.0000, 0.7116, 0.1157],
        [0.6574, 0.3451, 0.0453]])


tensor([[2.0000, 0.7116, 0.1157],
        [0.6574, 0.3451, 0.0453]])


tensor([[0.0000, 0.7116, 0.1157],
        [0.6574, 0.3451, 0.0453]])


## reshape funtion

In [101]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten() # 1D kr dega 16 elemnt ek sath

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# 3D
b = torch.rand([2,3,4])
b

tensor([[[0.9798, 0.5548, 0.6868, 0.4920],
         [0.0748, 0.9605, 0.3271, 0.0103],
         [0.9516, 0.2855, 0.2324, 0.9141]],

        [[0.7668, 0.1659, 0.4393, 0.2243],
         [0.8935, 0.0497, 0.1780, 0.3011],
         [0.1893, 0.9186, 0.2131, 0.3957]]])

In [105]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
# unsqeeze 
# use in models further 

c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

# Numpy and pytorch

In [109]:
import numpy as np

In [111]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [114]:
# conver tensor to numpy and store in b
b = a.numpy()
b

array([1, 2, 3])

In [115]:
type(b)

numpy.ndarray

In [116]:
c = np.array([1,2,3])
torch.from_numpy(c)

tensor([1, 2, 3])